# pyproject.toml
[tool.isort]
profile = "google"
use_parentheses = true
known_first_party = ["google3", "google"]
multi_line_output = 3

[tool.yapf]
based_on_style = "google"
indent_width = 2
column_limit = 80

